apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: campusconnect
spec:
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 3800
    targetPort: 5000
  type: LoadBalancer