apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: campusconnect
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 3500
    targetPort: 3000
  type: LoadBalancer