apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: campusconnect
  labels:
    app: frontend
    tier: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 3500
    targetPort: 3500
  type: LoadBalancer